### ISSUE TITLE
G-code parsing from Inkscape/gcodetools

### ISSUE THREAD

**Issue by makenb** [vangdfang/libcutter#11]
Thank You for this great tool!! I have been having issues using gcode generated in inkscape/gcodetools. whenever there was a G02 or G03 libcutter will choke and say: "looking for vector but got: ...", so looking at the code it seems Z movements are expected to be only on a G00 or G01 line by themselves and libcutter skips all other movements and goes to next line. or if there is a Z on G02 or G03 it does nothing and skips to next line. this seems non-standard. I would send a Diff but I'm more of a hardware guy and pointers confuse me ;-)...  gcodetools puts a Z on every movement so I just use a text editor to search and replace.

**Comment by rsaxvc** [comment]
Forgive me for my ignorance, but by 'Z' you mean the letter address 'Z' right?

Also, as it feels like ages since I've touched this, what does Z really mean for libcutter(or, what should it mean, I think we only deal with 2d cutters)? Should we silently skip it?

Also, could you post some working & nonworking example lines illustrating the issue?

**Comment by rsaxvc** [comment]
@makenb , could you please test the commit on the gcode_g02_g03_z_test branch ?

**Comment by makenb** [comment]
Thanks so much for looking at this! It looks like your fix would work for Z coming first in line, but the issue Im having is when the Z comes before I and J. I compiled the test branch and received same error:
`maken@T520:~/libcutter-gcode_g02_g03_z_test/util$ ./draw_gcode /dev/ttyUSB0 TestFile.gcode 
Divisor=120
r=0
Expected vector, got: Z-1.000000 I-97.596118 J-111.817982 F1000.000000
Expected vector, got: Z-1.000000 I-0.453576 J-0.630191
Expected vector, got: Z-1.000000 I0.353257 J-0.353257
Expected vector, got: Z-1.000000 I49.446247 J54.263997
Expected vector, got: Z-1.000000 I52.474371 J69.242460
Expected vector, got: Z-1.000000 I2.021352 J3.149244
Expected vector, got: Z-1.000000 I0.005952 J0.088033
Expected vector, got: Z-1.000000 I-2.766890 J-1.731920
`

Here is the gcode:
`G00 Z5.000000
G00 X150.185417 Y25.499709
M03 S1(Turn spray on)
G00 Z4.000000 (Fast pre-penetrate)
G01 Z-1.000000 F1000.0(Penetrate)
G03 X139.291008 Y34.143659 I-97.596118 J-111.817982 F1000.000000
G03 X138.288399 Y34.062498 I-0.453576 J-0.630191
G03 X138.305172 Y33.339972 I0.353257 J-0.353257
G03 X143.410590 Y29.094110 I49.446247 J54.263997
G03 X148.956078 Y25.221880 I52.474371 J69.242460
G03 X150.725133 Y24.637501 I2.021352 J3.149244
G03 X150.805876 Y24.772349 I0.005952 J0.088033
G03 X150.185417 Y25.499709 I-2.766890 J-1.731920
G01 X150.185417 Y25.499709 Z-1.000000
G00 Z5.000000
M05 (Turn spray off)`

If I remove the Zs on all G2 and G3 lines it works.
Thanks,
Makenb

**Comment by rsaxvc** [comment]
I'm sorry, I don't see any Zs on G02 or G03 lines for the g-code you posted(or, am I misunderstanding the G-code format? It's quite possible.).

Oh man, T520s are great. I'm on an x220 right now.

**Comment by makenb** [comment]
@rsaxvc 
Oh sorry,
I must have posted the corrected file. I will post intended gcode when I get home from work. 
For now the gcodetools inkscape plugin format always includes Z positions, example:
G00 X##.### Y##.### Z##.### (move)
G03 X##.### Y##.### Z##.### I##.### J##.### (ccw arc)

Thanks,
Makenb

**Comment by makenb** [comment]
@rsaxvc 
OK didn't have time yesterday, but here is gcode:
Here is the gcode:
`G00 Z5.000000
G00 X150.185417 Y25.499709
M03 S1(Turn spray on)
G00 Z4.000000 (Fast pre-penetrate)
G01 Z-1.000000 F1000.0(Penetrate)
G03 X139.291008 Y34.143659 Z-1.000000 I-97.596118 J-111.817982 F1000.000000
G03 X138.288399 Y34.062498 Z-1.000000 I-0.453576 J-0.630191
G03 X138.305172 Y33.339972 Z-1.000000 I0.353257 J-0.353257
G03 X143.410590 Y29.094110 Z-1.000000 I49.446247 J54.263997
G03 X148.956078 Y25.221880 Z-1.000000 I52.474371 J69.242460
G03 X150.725133 Y24.637501 Z-1.000000 I2.021352 J3.149244
G03 X150.805876 Y24.772349 Z-1.000000 I0.005952 J0.088033
G03 X150.185417 Y25.499709 Z-1.000000 I-2.766890 J-1.731920
G01 X150.185417 Y25.499709 Z-1.000000
G00 Z5.000000
M05 (Turn spray off)`

Yes the T520 is nice though at 5 years old is showing its age.

Maken

**Comment by rsaxvc** [comment]
I've updated the branch with a new style of parser I was meaning to try out.

Also, the key to code formatting with markdown is four spaces preceding each line. I think you need a blank line before and after each group of code-liens

**Comment by makenb** [comment]
Hi @rsaxvc,

Ive tried to compile new code but it fails:

    `maken@T520:~/Desktop/libcutter-gcode_g02_g03_z_test$ make
    Scanning dependencies of target cutter
    [  5%] Building CXX object lib/CMakeFiles/cutter.dir/serial_port.cpp.o
    [ 10%] Building CXX object lib/CMakeFiles/cutter.dir/device.cpp.o
    [ 15%] Building CXX object lib/CMakeFiles/cutter.dir/device_c.cpp.o
    [ 20%] Building C object lib/CMakeFiles/cutter.dir/btea.c.o
    [ 25%] Building CXX object lib/CMakeFiles/cutter.dir/device_sim.cpp.o
    Linking CXX shared library libcutter.so
    [ 25%] Built target cutter
    Scanning dependencies of target draw_gcode
    [ 30%] Building CXX object util/CMakeFiles/draw_gcode.dir/draw_gcode.cpp.o
    [ 35%] Building CXX object util/CMakeFiles/draw_gcode.dir/gcode.cpp.o
    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/gcode.cpp: In member function ‘xy   gcode::get_xy(std::map<char, float>&)’:
    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/gcode.cpp:391:43: error: in C++98 ‘target’   must be initialized by constructor, not by ‘{...}’
          xy target = { codes['X'], codes['Y'] };
                                           ^
    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/gcode.cpp: In member function ‘xy gcode::get_vector(std::map<char, float>&)’:
    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/gcode.cpp:396:34: error: in C++98 ‘t’ must     be initialized by constructor, not by ‘{...}’
      xy t = { codes['I'], codes['J'] };
                                  ^
    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/gcode.cpp: In member function ‘void gcode::process_g_code(std::map<char, float>&)’:
    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/gcode.cpp:516:29: error: ‘to_string’ was not declared in this scope
        msg.append(to_string(code));
                             ^
    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/gcode.cpp: In member function ‘void gcode::process_misc_code(std::map<char, float>&)’:
    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/gcode.cpp:545:29: error: ‘to_string’ was   not declared in this scope
        msg.append(to_string(code));
                             ^
    util/CMakeFiles/draw_gcode.dir/build.make:77: recipe for target     'util/CMakeFiles/draw_gcode.dir/gcode.cpp.o' failed
    make[2]: *** [util/CMakeFiles/draw_gcode.dir/gcode.cpp.o] Error 1
    CMakeFiles/Makefile2:149: recipe for target 'util/CMakeFiles/draw_gcode.dir/all' failed
    make[1]: *** [util/CMakeFiles/draw_gcode.dir/all] Error 2
    Makefile:76: recipe for target 'all' failed
    make: *** [all] Error 2
`

**Comment by makenb** [comment]
I added the compiler flag " -std=c++0x" to the CMakeLists.txt now it compiles.
However, when I try to run above gcode it just ejects the cutter mat and stops, no error 

Maken

**Comment by rsaxvc** [comment]
@makenb , there were a few pretty silly bugs in that commit. Since then, I got the simulator running, and have uploaded a new patch that renders some of the test images like the old one does. But now, Z codes control the 'toolhead' correctly. Could you retest the gcode_g02_g03_z_test branch? Sorry about the latency on this. I also removed the c++0x dependency - should now work on c++03 to at least c++11.

**Comment by makenb** [comment]
@rsaxvc,

Thats great! thanks so much for all your work. I tested it and it seems to work fine. I had to add 
"-std=c++11" to CMakeLists to compile, but It does work with no complaints. I think I have found another small bug but I will make a different report for that I think this bug is squashed. ;-P

Thank You,
Maken

**Comment by rsaxvc** [comment]
Can you send me the compiler error without the c++11 flag?

**Comment by makenb** [comment]
Yes Here it is:

`    maken@T520:~/Desktop/libcutter-gcode_g02_g03_z_test$ make

    [ 25%] Built target cutter

    [ 35%] Built target draw_gcode

    [ 45%] Built target draw_gcode_cv

    [ 50%] Building CXX object util/CMakeFiles/draw_svg.dir/draw_svg.cpp.o

    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/draw_svg.cpp: In function ‘svg_status_t curve_callback(void*, double, double, double, double, double, double)’:

    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/draw_svg.cpp:230:22: error: in C++98 ‘p1’ must be initialized by constructor, not by ‘{...}’

         xy p1 = { x1, y1 };

                          ^

    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/draw_svg.cpp:231:22: error: in C++98 ‘p2’ must be initialized by constructor, not by ‘{...}’

         xy p2 = { x2, y2 };

                          ^

    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/draw_svg.cpp:232:22: error: in C++98 ‘p3’ must be initialized by constructor, not by ‘{...}’

         xy p3 = { x3, y3 };

                          ^
     /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/draw_svg.cpp: In function ‘svg_status_t    quadratic_curve_callback(void*, double, double, double, double)’:

     /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/draw_svg.cpp:246:22: error: in C++98 ‘p1’ must be initialized by constructor, not by ‘{...}’

         xy p1 = { x1, y1 };

                          ^

    /home/maken/Desktop/libcutter-gcode_g02_g03_z_test/util/draw_svg.cpp:247:22: error: in C++98 ‘p2’ must be initialized by constructor, not by ‘{...}’

         xy p2 = { x2, y2 };

                          ^

    util/CMakeFiles/draw_svg.dir/build.make:54: recipe for target   'util/CMakeFiles/draw_svg.dir/draw_svg.cpp.o' failed

    make[2]: *** [util/CMakeFiles/draw_svg.dir/draw_svg.cpp.o] Error 1

    CMakeFiles/Makefile2:219: recipe for target 'util/CMakeFiles/draw_svg.dir/all' failed

    make[1]: *** [util/CMakeFiles/draw_svg.dir/all] Error 2

    Makefile:76: recipe for target 'all' failed

    make: *** [all] Error 2

`
