### ISSUE TITLE
Circle prints as rounded rectangle

### ISSUE THREAD

**Issue by squires** [vangdfang/libcutter#12]
I'm trying to use libcutter with my C. Personal with firmware v1.34. Curves aren't printing correctly. Below is an image of what I get when I try to print a circle. I'm using a slightly modified version of svg_tests/circle.svg to demonstrate the problem better: `<circle cx="200" cy="200" r="50" stroke="black" stroke-width="2" />`. I'm using the keys from the "Setting Up Libcutter" wiki page.

The output is pictured below. Anyone know what is wrong? Or what next steps I should take for troubleshooting?

!["Circle"](https://i.imgur.com/IW8YKPW.jpg)

**Comment by rsaxvc** [comment]
I would try to draw using the OpenCV backend - if you get a similar shape, it's probably an issue converting SVG into libcutter commands. If you get a wildly different shape, it's probably an issue between libcutter and the device.

Internally, libcutter supports only a handful of operations, like line and spline

**Comment by rsaxvc** [comment]
I made a modified test svg with your changes and ran it through the simulator, it correctly built the circle into spline segments which appear mostly round, so this looks like an issue converting into device commands, not SVG parsing.

**Comment by david-e-cox** [comment]
I realize this post is nearly 4 years old, but... I just built libcutter tonight and I get the exact same results for a circle.    Starting in inkscape and saving to "plain svg".    I also tried the ./utils/svg_tests/circle_squires.svg file and it cuts to the same shape as shown above (open sided rectangle, with chopped corners).   Cricut Personal@Version1.32

dave

**Comment by rsaxvc** [comment]
I haven't had time to look at this, though I do have an expression now. I have two theories:

- It's forming an ambiguous command for the machine, which picks the wrong path format.
- Somehow the wrong key is loaded, so the 4-point curve command might be interpreted as 4 separate cut-to commands.

If you have time, a few questions would help me:

- Does circle.svg cause the same issue?
- Is the long-cut(the one that is only attached to the rounded rect once, I will reference the free end as 6,30), the first segment cut?
- If you run it a second time without ejecting, does it directly follow the path around the rounded rectangle again, or does it go back to 6,30 as part of it?

**Comment by david-e-cox** [comment]
Yes, circle.svg causes the same issue, same pattern.

The long cut from the 6,30 corner is the first segment.

And I ran it a second time.  That time it makes the rounded rectangle again, and it doesn't cut back to the 6,30 point.   It actually closes the rectangle on the second run, as it's starting in right place for that open leg.

**Comment by david-e-cox** [comment]
I tried modifing the key values in .libcutter, just by changing a digit.  If the curve key is modified, no cuts at all are made.   If I modify the move and line keys, but leave the curve key valid, then it cuts the rounded rectangle, as it has been previously.

**Comment by rsaxvc** [comment]
> And I ran it a second time. That time it makes the rounded rectangle again, and it doesn't cut back to the 6,30 point. It actually closes the rectangle on the second run, as it's starting in right place for that open leg.

Thanks! In this case, the commands are being interpreted as cuts, but the points being sent are the 4 belonging to the beziers used to interpolate/estimate quadrants of a circle(we draw circles as 4 beziers).

Since the beziers' sweep an angle of 90 degrees, their points will be relatively shallow, and they'll form 3 connected line segments. I'd guess we're seeing a little more rounding from the drag-knife's tip being slightly behind center. I'm not 100% certain(and wouldn't be unless we plotted the bezier points on top), but I think that's what's going on.

>  If the curve key is modified, no cuts at all are made. If I modify the move and line keys, but leave the curve key valid, then it cuts the rounded rectangle, as it has been previously.

Excellent test, that confirms libcutter is using the key from the curve-key slot, but from the above, I'd guess the key in the curve-key slot is actually a line-key, not a curve-key. Could you please double check that you're using the right ones?

**Comment by david-e-cox** [comment]
I swapped the line and curve keys, and got the spiral below. 
![IMG_20220109_233450812](https://user-images.githubusercontent.com/34388548/148719858-38e8a72b-1259-4d75-96a6-2d8323f30871.jpg)

**Comment by david-e-cox** [comment]
Uncommenting line 87 in ./util/svg.cpp yeilds the values below.   I think that's got the bezier points in it, as well as the end points.  
![Screenshot from 2022-01-09 23-54-31](https://user-images.githubusercontent.com/34388548/148720165-5ffbc84b-8eb0-4551-87b9-41b0085631d0.png)

**Comment by rsaxvc** [comment]
Those points make sense - IIRC the first is the start, the last is the end. Since the end of each matches the start of the next that bit makes sense. The middle points make sense too for a quadrant's arc.

Since the geometry is right, it's got to be a key issue. I don't know what to make of your spiral though.

**Comment by squires** [comment]
Is it possible that different Cricuts might have different keys? (If the keys aren't in the firmware but perhaps ROM?) These are the keys that have been around (and increasingly obscure since sites have gone offline) for many years.

**Comment by david-e-cox** [comment]
I got a circle to cut, but I had to offset it to keep it on the paper and it still drags that first cut into it.   (I actually didn't see it until I posted that image.... it is the off-paper cut in the green area)  

I'm thinking it could be a scaling issue with the bezier points.   There is a 1/100 scaling at line 149 in svg.cpp, and 100 DPI setting in the device_sim.cpp file.    But the device_c.cpp file has 404 as the INCHES_TO_C_UNITS variable.    If I change the scaling lines in svg.cpp to 
   buf.x /= 404;
   buf.y /= 404;

I get a circle.  It's smaller, off the page, and has the cut from the first point.   But it's round ;)    I've got to sign off tonight.   But I'll check back here.     And I'll post if get anything else of interest.  Thanks!

**Comment by rsaxvc** [comment]
> Is it possible that different Cricuts might have different keys? (If the keys aren't in the firmware but perhaps ROM?

I don't think so. There's no key exchange or derivation on this vintage device, so both ends would need to understand the keys. It's possible they changed across a firmware version.

> These are the keys that have been around (and increasingly obscure since sites have gone offline) for many years.

That's no good. There was at least one website that had chosen an incorrect set of four once before, but I don't recall which. I think there's actually 8 to choose from, IIRC the others let you do things like slow-start cuts, but libcutter doesn't use them yet.

> There is a 1/100 scaling at line 149 in svg.cpp, and 100 DPI setting in the device_sim.cpp file. But the device_c.cpp file has 404 as the INCHES_TO_C_UNITS variable. If I change the scaling lines in svg.cpp to buf.x /= 404; buf.y /= 404;

I believe that 1/100x scaling in SVG is our conversion to inches(I think assuming 100DPI is rarely correct, and a subset of what SVG supports). I think most SVGs are actually 72 or 96 DPI though.

There are 404 geared/stepper ticks per inch, so the conversion from SVG to cutter units is indeed *=(404/100).

**Comment by david-e-cox** [comment]
Thanks, the different units make more sense now,  one for comming in from SVG, and one for going out to the device steps.
I ran through some of the other keys, the "lift cutter" curve key does provide the proper shape.  But as it starts every cut with the blade up there are gaps in the cut.   Maybe this is how it's always worked?    Or there is something fishy with my firmware?   I am at 1.32, and I've seen reference to 1.34.  

![IMG_20220110_200712189](https://user-images.githubusercontent.com/34388548/148863994-f664355d-1cf0-4445-94c6-22b07aad5918.jpg)

**Comment by rsaxvc** [comment]
> But as it starts every cut with the blade up there are gaps in the cut. Maybe this is how it's always worked? Or there is something fishy with my firmware? I am at 1.32, and I've seen reference to 1.34.

I believe you're now using a curve-key, but the one that starts with the blade up and gently lowers it to start. IIRC, there were two more, one that lifts at the end, and another that applies full pressure before traveling(the one libcutter expects)

**Comment by david-e-cox** [comment]
Thanks!   That was it.   I worked through the other available keys and found one that keeps the blade down and implements the beizer curve properly.  

I do still get a cut from the start position over to the first segment of the circle.   I looked at the code in svg.cpp and most calls to the class curve_to() method have current_pos as the first argument.   In render_ellipse_callback(), however, it calls curve_to() with the first control point as the initial argument.   

I put a move_to() in that ellipse_callback prior to starting the first segment of the ellipse.   That makes the circle and ellipse test cases come out clean.

**Comment by rsaxvc** [comment]
Awesome! Could you please put up a patch  to handle that first move?

**Comment by david-e-cox** [comment]
Yes, I'll pull a pull request up tonight.   It's a quick fix.   Thanks!

**Comment by rsaxvc** [comment]
Thank you both for finding and fixing this, I've merged #46 . This issue was a combination of a swapped curve-key-set and forgetting to move to the start of a curve cut before cutting.

**Comment by ellisgl** [comment]
I'm showing this issue when trying to cut out the circle, it's kind of like a diamond. Running V2.34 on my Expression
Also it's trying to puts stuff at the upper right. Here's a test that I tried 
![honeycomb](https://user-images.githubusercontent.com/94559/182278729-24a07193-a4ac-448d-b85d-1609b1fefccc.svg)

**Comment by ellisgl** [comment]
Got the circle to go by swapping the curve keys to "key 5". 
After swapping line keys to "key 3" to see see if fixed a scaling issue, that wasn't the case and all that did was move it up and to the right even more...
