### ISSUE TITLE
Need CI build tests

### ISSUE THREAD

**Issue by rsaxvc** [vangdfang/libcutter#26]
As a hardware device, it's a little tricky to test changes, but even compile-checks would be useful for OSX/Win32/Linux. I believe @citelao might have some ideas.

**Comment by citelao** [comment]
I've got a good number of tests on the easily-verifiable side for my Node driver---I test GCode parsing, my BTEA implementation, sanity checks in my Cutter (e.g. "out-of-bounds" & "don't cut without a mat" errors).

But I don't think there's a good way to do anything more than that.

I plan to stand up CI builds anyway, so those will be a good start, as you point out.

**Comment by rsaxvc** [comment]
Even just testing building and the software end of things will be a huge improvement.

**Comment by citelao** [comment]
Fixed! See also #33 #34 #35 for follow-up work.
