### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by jatomusic** [vangdfang/libcutter#4]
I've noticed when i create text SVG's in inkscape, not all the lines will cut. It is happening to me with the word Liberty. Also this is a possible feature request, or if someone can just post how to do it. When using the draw_svg_cv simulator, it is just too small a window, it would be great if it simulated a 12x12 in cut size, or if it had options to give it dimentions. If it does then where would i find the syntax? Anyways this wonderful package has allowed me to cut with my machine, although it took me forever to find any docs on it since it all has been taken offline, particularly key related info, i do understand why, any who i would love to chat with anyone associated with this project. IRC maybe?

**Comment by rsaxvc** [comment]
Hmm, this hasn't been touched in 8 years, and I don't think we have the file required to reproduce. SVG parsing is pretty hokey though, so it's probably real. Can reopen or open anew as needed.
