### ISSUE TITLE
Support for new generation of machines

### ISSUE THREAD

**Issue by timonsku** [vangdfang/libcutter#44]
I couldn't find and discussions or info on newer generations of Cricut machines. Has this ever been looked into?
Is there any info if they share any of the old protocol or are they complete re-designs? I could possibly help adding support, I have access to a Maker model.

**Comment by rsaxvc** [comment]
They do use a different protocol.

I'm not opposed to adding support for it, but we would need an interested developer (you?) and a clean source for protocol documentation to start from.

There is a discord group called cut freedom, and they are looking into such things. You might check with them.

**Comment by timonsku** [comment]
Thanks for the info, I'll check that out!
